---

################################################################################
#  description: Enables EPEL Repository on CentOS7x
#  usage: ansible-playbook CentOS7x_Enable-EPEL-Repository-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Enables EPEL Repository on CentOS7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Install yum packages
# REF: http://docs.ansible.com/ansible/yum_module.html
######################################################

  - name: Install wget if that package is not already present or update existing if needed
    yum:
      name=wget
      state=latest

  - name: Install epel-release-7-10.noarch.rpm if that package is not already present
    yum:
      name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-10.noarch.rpm
      state=present
