---

################################################################################
#  description: Run UI-for-Docker https://github.com/kevana/ui-for-docker
#  usage: ansible-playbook Docker_UIforDocker-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Run UI-for-Docker https://github.com/kevana/ui-for-docker
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# docker - manage docker containers
# REF: http://docs.ansible.com/ansible/docker_container_module.html
###################################################################

  - name: ui-for-docker container
    docker_container:
      name: ui-for-docker
      image: uifd/ui-for-docker
      state: started
      exposed_ports:
      - 9000
      ports:
      - "9000:9000"
