---

################################################################################
#  description: Installs/applies OS updates and patches on RHEL7x
#  usage: ansible-playbook RHEL7x_Apply-OS-Updates-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Apply OS updates and patches on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Install yum packages
# REF: http://docs.ansible.com/ansible/yum_module.html
######################################################

  - name: Update / upgrade all existing installed packages
    yum:
      name=*
      state=latest

  - name: Install yum-utils if that package is not already present or update existing if needed
    yum:
      name=yum-utils
      state=latest


# Execute command(s)
# REF: http://docs.ansible.com/ansible/command_module.html
##########################################################

  - name: Remove old kernels from the OS keeping only the last most recent two
    command: /usr/bin/package-cleanup --oldkernels --count=2 -y


# Set attributes of files
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

  - name: Remove annoying warning message in cases where yum is run manually
    file:
      path=/etc/sysconfig/rhn/systemid
      state=touch
      mode=0644
