---

################################################################################
#  description: Installs Redis on RHEL7x
#  usage: ansible-playbook RHEL7x_Install-Redis-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere RedisPassword=DesiredPasswordHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Install Docker on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Install yum packages
# REF: http://docs.ansible.com/ansible/yum_module.html
######################################################

  - name: Install redis
    yum:
      name=redis
      state=latest


# Use the template module to populate files with data
# REF: http://docs.ansible.com/ansible/template_module.html
###########################################################

# /etc/redis.conf
  - name: Fill in the variables and copy templates/Redis/redis.conf.j2 to remote /etc/redis.conf
    template:
      src=templates/Redis/redis.conf.j2
      dest=/etc/redis.conf
      owner=root
      group=root
      mode=0644


# Restart firewalld to make sure it is running OK before changing any rules
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Ensure the firewalld service is enabled and re-started before changing any rules
    service:
      name=firewalld
      enabled=yes
      state=restarted


# Update the firewalld configuration
# REF: http://docs.ansible.com/ansible/firewalld_module.html
############################################################

  - name: Update firewall to allow port TCP 6379 for incoming Redis connections
    firewalld:
      port=6379/tcp
      permanent=true
      immediate=yes
      state=enabled
      zone=public


# Enable and start redis
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Enable and start the redis service
    service:
      name=redis
      enabled=yes
      state=restarted
      # Note: Verify docker via SSH command line:
      # systemctl status redis
