---

################################################################################
#  description: Installs Jenkins on RHEL7x
#  usage: ansible-playbook RHEL7x_Install-Jenkins-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Install Jenkins on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Install or confogire repository used on the OS by yum
# REF: https://docs.ansible.com/ansible/yum_repository_module.html
##################################################################

# /etc/yum.repos.d/jenkins.repo
  - name: Install repository jenkins
    yum_repository:
      name: jenkins
      description: Jenkins repository
      file: jenkins
      baseurl: http://pkg.jenkins.io/redhat
      enabled: yes
      gpgcheck: yes
      gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key


# Install yum packages
# REF: http://docs.ansible.com/ansible/yum_module.html
######################################################

  - name: Install jenkins
    yum:
      name=jenkins
      state=latest


# Restart firewalld to make sure it is running OK before changing any rules
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Ensure the firewalld service is enabled and re-started before changing any rules
    service:
      name=firewalld
      enabled=yes
      state=restarted


# Update the firewalld configuration
# REF: http://docs.ansible.com/ansible/firewalld_module.html
############################################################

  - name: Update firewall to allow port TCP 8080 for incoming Jenkins connections
    firewalld:
      port=8080/tcp
      permanent=true
      immediate=yes
      state=enabled
      zone=public


# Enable and start elasticsearch.service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Enable and start the jenkins.service service
    service:
      name=jenkins.service
      enabled=yes
      state=restarted
      # Note: Command line verification:
      # systemctl status elasticsearch.service
      # cat /var/log/elasticsearch/graylog2.log
      # curl -XGET 'http://IPAddressHere:9200/_cluster/health?pretty=true'
