---

################################################################################
#  description: Installs RDP Services on RHEL7x
#  usage: ansible-playbook RHEL7x_Install-RDP-Services-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Install RDP Services on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Install yum packages
# REF: http://docs.ansible.com/ansible/yum_module.html
######################################################

  - name: Install Server with GUI group packages
    yum:
      name="@^Server with GUI"
      state=present
      # Note: RHEL7x has two (2) types of group lists "package groups" and "environment groups"
      # Use: yum group list
      # REF: http://docs.ansible.com/ansible/yum_module.html#notes

  - name: Install the xrdp package
    yum:
      name=xrdp
      state=latest

  - name: Install the tigervnc-server package
    yum:
      name=tigervnc-server
      state=latest

  - name: Install the Microsoft Visual Studio Code via remote rpm
    yum:
      name=https://az764295.vo.msecnd.net/stable/e6b4afa53e9c0f54edef1673de9001e9f0f547ae/code-1.3.1-1468329898.el7.x86_64.rpm
      state=present


# Restart firewalld to make sure it is running OK before changing any rules
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Ensure the firewalld service is enabled and re-started before changing any rules
    service:
      name=firewalld
      enabled=yes
      state=restarted


# Update the firewalld configuration
# REF: http://docs.ansible.com/ansible/firewalld_module.html
############################################################

  - name: Update firewall to allow port TCP 3389 for incoming RDP connections
    firewalld:
      port=3389/tcp
      permanent=true
      immediate=yes
      state=enabled
      zone=public


# Enable and start xrdp.service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Enable and start the xrdp.service service
    service:
      name=xrdp.service
      enabled=yes
      state=restarted
